services:
  index:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: index_app
      volumes:
        - .:/var/www/html
      ports:
        - "80:80"
      environment:
        #APP_ENV: local
        #APP_DEBUG: yes
        #APP_KEY: base64:YOUR_APP_KEY
        COMPOSER_ALLOW_SUPERUSER: yes
        MYSQL_HOST: mysql
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_USER: ${DB_DATABASE}
        MYSQL_PASSWORD: ${DB_PASSWORD}
      networks:
        - app-network
      # command: bash -c "composer install --no-dev --optimize-autoloader && apache2-foreground"
  mysql:
    image: mysql:8.0
    container_name: index_database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password_here
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./storage/dumps:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - app-network

networks:
  app-network:

volumes:
  mysql_data: